# Generated by Django 3.1.6 on 2021-02-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('pub_datetime', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('fee', models.PositiveIntegerField()),
                ('matching', models.CharField(blank=True, default=None, max_length=30, null=True, unique=True)),
                ('writer', models.ForeignKey(db_column='writer', default='탈퇴한 회원', on_delete=django.db.models.deletion.SET_DEFAULT, to='tempApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
                ('pub_datetime', models.DateTimeField(auto_now_add=True)),
                ('fee', models.IntegerField()),
                ('q_no', models.ForeignKey(db_column='q_no', on_delete=django.db.models.deletion.CASCADE, to='tempApp.question')),
                ('writer', models.ForeignKey(db_column='writer', default='탈퇴한 회원', on_delete=django.db.models.deletion.SET_DEFAULT, to='tempApp.member')),
            ],
        ),
    ]
